### ISSUE TITLE
上拉分页会crash

### ISSUE THREAD

**Issue by Mdany** [Mdany/client-android#1]
05-04 18:31:06.361 11981-11981/com.chenyu.monster E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.chenyu.monster, PID: 11981
                                                                    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{11f25afa position=167 id=-1, oldPos=167, pLpos:167 scrap [attachedScrap] tmpDetached no parent}
                                                                        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4251)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4382)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                                        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2864)
                                                                        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                        at android.view.View.layout(View.java:15795)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5042)
                                                                        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:584)
                                                                        at android.view.View.layout(View.java:15795)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5042)
                                                                        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
                                                                        at android.view.View.layout(View.java:15795)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5042)
                                                                        at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
                                                                        at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
                                                                        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
                                                                        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
                                                                        at android.view.View.layout(View.java:15795)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5042)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                        at android.view.View.layout(View.java:15795)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5042)
                                                                        at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
                                                                        at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
                                                                        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
                                                                        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
                                                                        at android.view.View.layout(View.java:15795)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5042)
                                                                        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
                                                                        at android.view.View.layout(View.java:15795)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5042)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                        at android.view.View.layout(View.java:15795)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5042)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                        at android.view.View.layout(View.java:15795)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5042)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                        at android.view.View.layout(View.java:15795)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5042)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                        at android.widget.Linear

**Comment by Mdany** [comment]
RecycleView's bug.
This bug is still not fixed in 23.1.1.
A comment workaround would to catch the exception.
RXJava+Retrofit replace okHttp

**Comment by EmiFree** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
2ZYH3, @zeewell, @RainGather, @TanLidong, @harmy, @finlay-liu, @IJJNPY, @zhiyue, @ww12358, @lisidi, @godIsAProgrammer, @godontop, @xuanyuansen, @kirinay, @czhou, @wiki6, @ruanjianershu, @wandaoyi, @albertww, @edwards414
